#+TITLE:Condensed Math
#+AUTHOR: Dmytro Soldovnichenko
#+Date: <2020-01-23 Do>
#+TODO: LEARN WRITE | DONE
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
* Quick links
- [[Condenced Math general (Set theory ⋃ Category theory)][Condenced Math general (Set theory ⋃ Category theory)]]
- [[Condenced Analysis][Condenced Analysis]]
- [[Condenced Linear algebra][Condenced Linear algebra]]
- [[Condenced {Discrete math ⋃ Numerical analysis}][Condenced {Discrete math ⋃ Numerical analysis}]]
* English-German disambiguation :TODO:
Most terminologies are literally the same in both English and German, however, there
are some naming conventions in English which are /isomorphic/ but not identical to German, that being:

- *Körper* is a *Field*
- ...but a *Vector space* *(Vectorraum)*, is not a *Vector field*. (Latter being a *Vektorfeld*, a function that assigns a vector
over every point in a given /space/).

Further list translations:
- *Schiefkörper* is a *Skew field* or *Division ring*
- *Halbkörper* is a *Semifield*
- *Fastkörper* is a *Near-ring* /sometimes written as nearring or near ring, there
  is some serious pun potential./

* Quick note on capitalization/syntax rules :TODO:
Start sentences and blocks with a capital letter. Terms such as *Sets*, *Rings*,
*Vectors* should be capitalized or even emphasised *in bold*. However, *Set
theory* or any multiword terms only need the first word be capitalized. Names
override the rule as they are always capitalized. This is done to make it look
similar enough to German syntax, which simplifies my life. But note, I make some
slips and some words may be mistakenly capitalized — you're free to correct me.
/note: if a topic occurs somewhere else, the best thing to do is to link it to an entry here, if such doesn't exit, create one./
* Transferrable math conventions (extension of syntax rules)
- I use square cup =\sqcup= to denote 'disjoint unions'.
- $\mathbb{K}$ stands for "either $\mathbb{R}$ or $\mathbb{C}$". It's a "macro",
  an ad-hoc substitution designed to shorten some definitons or proofs.
* Condenced Math general (Set theory ⋃ Category theory)

** Elementary Set Theory
*** Notes on algebraic structures:
**** Note 1: on extending algebraic structures
fields and rings can be thought of as extensions of more primitive definitions
such as groups, half-groups, monoids and so on. This is useful in math, because a lot of times, fields
are mere "special cases". This also means, there is no definitive way to learn
this stuff in mathematics, you can mix and match definitions to make your own
version of definitions that may or may not be easy to learn.
The bottom-up approach is useful in a sense that you can still name the
structure you're working with even if your initial (optimistic) assumption was
incorrect or you're working with minimal information.
**** Note 2: hierarchy of algebraic structures
you can form a hierarchy of algebraic structures for learning convenience

|-------+-----------+-------|
| Magma | Semigroup | Group |
|-------+-----------+-------|

Ring-to-Field correpsondence "spiritual successor"

|--------------+------------+------------|
| Ring         | Halbring   | Fastring   |
|--------------+------------+------------|
| Schiefkörper | Halbkörper | Fastkörper |
|--------------+------------+------------|

**** Note 3: "space" means little on its own
We don't go that much into detail when studying this, but *space* is also a
frequently-used terminology without much meaning as-is, but by adding an adjective, you get
some /structure/ (Topology, Metric, Vectors being examples said structures).
**** Note 4: a lot of writing is put on hold since this Wiki page exists
https://en.wikipedia.org/wiki/Outline_of_algebraic_structures
*** Space(s)
space is a set which has some underlying structure, such as a vector, metric, or topology.
**** LEARN Topological space

**** Metric space
**** Vector space

*** LEARN Monoid (I only know it exists, and it's not strictly necessary to learn)
metamath link: http://us.metamath.org/mpegif/df-mgm.html
*** Halbgruppe
*** Gruppe

*** Ring
*** Ring-like structures (abelian Ring and Schiefkörper,)

*** Körper /eng: Field/
**** Definition
*Axioms:*

Let $K$ be a field /Körper/ then the following statements hold true:
- *Commutativity:* addition and multiplication is commutative, i.e.
  - $a + b = b + a$
- *Distributivity:*

**** Common Field properties
/a Field is, or can be:/
- *Ordered* /(geordnet)/: \\
  A Set $\mathbb{K}$ is ordered if:
  - $(i) \quad a \in \mathbb{K}^{+} \veebar a = 0 \veebar -a \in \mathbb{K}^{+}$
  - $(ii) \quad a,b \in \mathbb{K}^{+} \, \Rightarrow \, a + b \in
    \mathbb{K}^{+} \, \land \; ab \in \mathbb{K}^{+}$
  /note: sometimes it's useful to remember, that/ $a < b \, \Rightarrow \, b - a \in \mathbb{K}^{+}$
- *Complete* /(ordnungs*vollständig)/: \\
  An ordered Set $\mathbb{K}$ is complete if: \\
  $\exists A,B \in \mathbb{K} \quad A,B \ne \emptyset \quad \forall a,b \in \mathbb{K} : a \geq b \quad \forall a \in A
   \quad \forall b \in B \quad \Rightarrow \quad \exists x \in \mathbb{K} : a \leq x \leq b
   \quad \forall a \in A \quad \forall b \in B$
- *Inductive* /induktiv/: \\
  $M\subset \mathbb{K}$ is inductive if:
  - $(i) \quad 0 \in M$
  - $(ii) \quad \forall a \in M : \, a+1 \in M$
**** Zahlmenge /= Sets of numbers/
- $M_{ind} := \{ x\subseteq \mathbb{R}| \, x \: inductive \: Set \: of \: X \}$
- \[\mathbb{N} := \bigcap_{X \in M_{ind}} X\]
  this definition implies: $0 \in \mathbb{N}$, but different books provide different
  definitions. \\
  shorthand for $\mathbb{N} \setminus \{0\}$ is $\mathbb{N}^{*}$, it's safer to
  always define itt beforehand in each exam, in order to avoid ambiguity.
- another interesting property I figured out after asking the professor about
  it, but be careful if it's not actually true:
  \[O := \{x \subset R | x \: is \: ordered \} \\
  \mathbb{Q} = \bigcap_{X \in O} X\]
*** Elementary Set logic

*** * "$\sqcup$" Disjoint union, "$\veebar$" Disjoint or

/nifty notation/
Let $A,B$ be Sets. "$\sqcup$" denotes that a union is disjoint (components share
no common elements). It does not "make" sets disjoint, so you might need to
prove they are disjoint first.

\[A \cap B = \emptyset \Rightarrow A \cup B \Leftrightarrow A \sqcup B\]

/similarly, (kinda sloppy notation)/

\[ \bigsqcup_{A \subset U} A\; \Rightarrow \; \forall A_{i}, A_{j} \; \in \; \bigsqcup_{A_{i} \subset U} A_{i}:\, i\not = j \quad A_{i} \cap A_{j} = \emptyset \]
**** Complement
/Since mathematicians are often pretty lazy, it's not uncommon to stumble upon some abbreviations. I consider "x is a complement of A" to be such shorthand for
an otherwise clumsy notation/.

Let $U,A$ be Sets such that $A \subset U$. Now, the complement of $A$ is defined as:

$A^{C}=\{x \in U | x \notin A \}$

or more generally,

$U \supset \alpha^{C} =\{x \in U | x \notin \alpha\}$.

the important takeaway is that

$U = A \sqcup A^{C}$ which can be also written as: $U = (U \cap A) \sqcup (U \setminus
A)$ \\
/the latter represents "$U$ without $A$" or "complement of $A$" as we have already
discussed/. And since any subset of $U$ and its complement are disjoint which
is trivial to prove: $A\cap A^{C}=\emptyset$,
hence the complement of a complement is itself:

$(A^{C})^{C} = A$ (/note:/ $A$ is simply $U \setminus A^{C}$). Kinda neat, huh?
*** Relations
https://en.wikipedia.org/wiki/Binary_relation
**** Equivalence relation
https://en.wikipedia.org/wiki/Equivalence_relation

Let $\sim \subset (\mathbb{R}, \mathbb{R})$, /alternatvely: $\sim \subset
\mathbb{R}^{2}$, (all we need is an ordered pair)/  \\
be a Binary relation. Such Relation is an
Equivalence relation if it satisfies: \\
$\forall a,b,c \in \mathbb{R}$
- Reflexive property: $a \sim a$
- Symmetry: $a\sim b \Rightarrow b\sim a$
- Transitive property: $a\sim b\sim c \Rightarrow a\sim c$


Related to Equivalence relation:

- Equivalence class: $[a] := \{x \in X | a \sim x\}$
- Quotient set: $X / \sim := \{[x]|x \in X\}$

* Condenced Analysis
** Sequences
** Series
** Convergence
** Continuity
** Differentiability
** Riemann integral

* Condenced Linear algebra

** Introduction
Before reading anything, just watch:
https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab \\
Linear Algebra is an interesting subject that broadens your horizon if you first
studied analyisis. One possible way to go around studying it is through the lens
of Category theory -- the alternative view to look at mathematics as a whole
(the "standard view" being Set theory).

one of the most important concepts to understand are:
- Linear (in)dependance
- Linear equation
- Linear system
- Relations between Matrices and Linear systems.

as long as you /understand/ these things, the rest of Linear algebra should be
easier to grasp (hopefully).

** Tiny bit of combinatorics
this is useful for understanding Leibniz's formula for calculating the
Determinant.
there are transpositions and permutations.

** Gauss-Jordan algorithm
this is something you'll be doing a lot, so get used to it.


** Intro to Matrices
*** Definition
$M(...)$ is a Set of matrices, explained below \\
- a Real-valued, $a \times b$ Matrix $A$ will be denoted as $A \in M(a \times b,
  \mathbb{R})$
- if I'm lazy, I'll just leave dots to assume any /sound/ (sensible) definition
  of a matrix.
- a (row) /vector/ $b$, often written as $\vec{b}$ is defined as $b \in M(1 \times n,
  \mathbb{K})$ column vectors are row vectors when /transposed/.
*** Matrix operators :TODO:
- you can add matrices together, or decompose a matrix into a sum, make sure the
dimensions are right: $A+B = C \implies B + A = C \quad A,B,C \in M(...)$
- you can also multiply matrices (important: *read left to right*), but not all Matrices commute: $C = AB
  \not\Rightarrow BA = C \quad A,B,C \in M(...)$
- you can multiply a vector by a matrix (since a vector is pretty much a Matrix
  in a mathematical sense.): $Ax = b$ is a standard way to write
  down a  System of linear equations for a known b and A, and an unknown vector
  b

  /(sometimes written down as $A \vec{x} = \vec{b}$ to distinguish scalars from
  vectors./
- you can transpose matrices, flipping their size values. $b = a^{T}, \; a \in
  M(1 \times  n, \mathbb{K}) \Rightarrow b \in M(n \times 1, \mathbb{K})$
- you can multiply a matrix by a scalar, but that's just vanilla basic stuff.
*** Dimension
*** Rank
*** Span

** Linear transformation
*** Definition
- just watch
  https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab
- I guess this applies to all Linear algebra, but alas.
- note: any map can be viewed through the lense of category theory as a
  Morphism, specifically a Homomorphism.

** Matrix ⇔ Linear mapping
** rng() <- Ring? Rang? ≠ Rank
** Morphisms (move to Category theory)

*** Endomorphism
**** Automorphism

*** Homomorphism
*** Isomorphism
** Scalar product(s)
** Hermetic-Bilinear-Sesquilinear functions
** Orthogonality

** Gram-Schmidt process
∫{}<>[]`´() /from:/ /to:/ /of/
* Condenced {Discrete math ⋃ Numerical analysis}
** Numerical stability
