#+TITLE:Condensed Math
#+AUTHOR: Dmytro Soldovnichenko
#+Date: <2020-01-23 Do>
#+TODO: LEARN WRITE | DONE
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
* Quick links
- [[Condenced Math general (Set theory ⋃ Category theory)][Condenced Math general (Set theory ⋃ Category theory)]]
- [[Condenced Analysis][Condenced Analysis]]
- [[Condenced Linear algebra][Condenced Linear algebra]]
- [[Condenced {Discrete math ⋃ Numerical analysis}][Condenced {Discrete math ⋃ Numerical analysis}]]
* English-German disambiguation :TODO:
Most terminologies are literally the same in both English and German, however, there
are some naming conventions in English which are /isomorphic/ but not identical to German, that being:

- *Körper* is a *Field*
- ...but a *Vector space* *(Vectorraum)*, is not a *Vector field*. (Latter being a *Vektorfeld*, a function that assigns a vector
over every point in a given /space/).

Further list translations:
- *Schiefkörper* is a *Skew field* or *Division ring*
- *Halbkörper* is a *Semifield*
- *Fastkörper* is a *Near-ring* /sometimes written as nearring or near ring, there
  is some serious pun potential./

* Quick note on capitalization/syntax rules :TODO:
Start sentences and blocks with a capital letter. Terms such as *Sets*, *Rings*,
*Vectors* should be capitalized or even emphasised *in bold*. However, *Set
theory* or any multiword terms only need the first word be capitalized. Names
override the rule as they are always capitalized. This is done to make it look
similar enough to German syntax, which simplifies my life. But note, I make some
slips and some words may be mistakenly capitalized — you're free to correct me.
/note: if a topic occurs somewhere else, the best thing to do is to link it to an entry here, if such doesn't exit, create one./
* Condenced Math general (Set theory ⋃ Category theory)

** Elementary Set Theory
*** Notes on algebraic structures:
**** Note 1: on extending algebraic structures
fields and rings can be thought of as extensions of more primitive definitions
such as groups, half-groups, monoids and so on. This is useful in math, because a lot of times, fields
are mere "special cases". This also means, there is no definitive way to learn
this stuff in mathematics, you can mix and match definitions to make your own
version of definitions that may or may not be easy to learn.
The bottom-up approach is useful in a sense that you can still name the
structure you're working with even if your initial (optimistic) assumption was
incorrect or you're working with minimal information.
**** Note 2: hierarchy of algebraic structures
you can form a hierarchy of algebraic structures for learning convenience

|-------+-----------+-------|
| Magma | Semigroup | Group |
|-------+-----------+-------|

Ring-to-Field correpsondence "spiritual successor"

|--------------+------------+------------|
| Ring         | Halbring   | Fastring   |
|--------------+------------+------------|
| Schiefkörper | Halbkörper | Fastkörper |
|--------------+------------+------------|

**** Note 3: "space" means little on its own
We don't go that much into detail when studying this, but *space* is also a
frequently-used terminology without much meaning as-is, but by adding an adjective, you get
some /structure/ (Topology, Metric, Vectors being examples said structures).
**** Note 4: a lot of writing is put on hold since this Wiki page exists
https://en.wikipedia.org/wiki/Outline_of_algebraic_structures
*** Space(s)
space is a set which has some underlying structure, such as a vector, metric, or topology.
**** LEARN Topological space

**** Metric space
**** Vector space

*** LEARN Monoid (I only know it exists, and it's not strictly necessary to learn)
metamath link: http://us.metamath.org/mpegif/df-mgm.html
*** Halbgruppe
*** Gruppe

*** Ring
*** Ring-like structures (abelian Ring and Schiefkörper,)

*** Körper /eng: Field/
**** Definition
*Axioms:*

Let $K$ be a field /Körper/ then the following statements hold true:
- *Commutativity:* addition and multiplication is commutative, i.e.
  - $a + b = b + a$
- *Distributivity:*

**** Common Field properties
/a Field is, or can be:/
- *Ordered* /(geordnet)/: \\
  A Set $\mathbb{K}$ is ordered if:
  - $(i) \quad a \in \mathbb{K}^{+} \lor a = 0 \lor -a \in \mathbb{K}^{+}$
  - $(ii) \quad a,b \in \mathbb{K}^{+} \, \Rightarrow \, a + b \in
    \mathbb{K}^{+} \, \land \; ab \in \mathbb{K}^{+}$
  /note: sometimes it's useful to remember, that/ $a < b \, \Rightarrow \, b - a \in \mathbb{K}^{+}$
- *Complete* /(ordnungs*vollständig)/: \\
  An ordered Set $\mathbb{K}$ is complete if: \\
  $\exists A,B \in \mathbb{K} \quad A,B \ne \emptyset \quad \forall a,b \in \mathbb{K} : a \geq b \quad \forall a \in A
   \quad \forall b \in B \quad \Rightarrow \quad \exists x \in \mathbb{K} : a \leq x \leq b
   \quad \forall a \in A \quad \forall b \in B$
- *Inductive* /induktiv/: \\
  $M\subset \mathbb{K}$ is inductive if:
  - $(i) \quad 0 \in M$
  - $(ii) \quad \forall a \in M : \, a+1 \in M$
**** Zahlmenge /= Sets of numbers/
- $M_{ind} := \{ x\subseteq \mathbb{R}| \, x \: inductive \: Set \: of \: X \}$
- \[\mathbb{N} := \bigcap_{X \in M_{ind}} X\]
  this definition implies: $0 \in \mathbb{N}$, but different books provide different
  definitions. \\
  shorthand for $\mathbb{N} \backslash \{0\}$ is $\mathbb{N}^{*}$, it's safer to
  always define itt beforehand in each exam, in order to avoid ambiguity.
- another interesting property I figured out after asking the professor about
  it, but be careful if it's not actually true:
  \[O := \{x \subset R | x \: is \: ordered \} \\
  \mathbb{Q} = \bigcap_{X \in O} X\]
** Elementary Set logic

*** Disjoint union

/nifty notation/
Let $A,B$ be Sets. "$\sqcup$" denotes that a union is disjoint (components share
no common elements). It does not "make" sets disjoint, so you might need to
prove they are disjoint first.

$A \sqcup B$ iff $A \cap B = \emptyset$

*** Complement
/Since mathematicians are often pretty lazy, it's not uncommon to stumble upon some abbreviations. I consider "x is a complement of A" to be such shorthand for
an otherwise clumsy notation/.

Let $U,A$ be Sets such that $A \subset U$. Now, the complement of $A$ is defined as:

$A^{C}=\{x \in U | x \notin U \}$

or more generally,

$\alpha^{C}\subset U =\{x \in U | x \notin \alpha\}$.

the important takeaway is that

$U = A \sqcup A^{C}$ which can be also written as: $U = (U \cup A) \sqcup (U \backslash
A)$ \\
/the latter represents "$U$ without $A$" or "complement of $A$" as we have already
discussed/. And since Any subset of $U$ and its complement are disjoint which
is trivial to prove: $A\cap A^{C}=\emptyset$,
Hence the complement of a complement is itself:

$(A^{C})^{C} = A$ ($A$ is simply $U \backslash A^{C}$). Kinda neat, huh?
* Condenced Analysis
** Sequences
** Series
** Convergence
** Continuity
** Differentiability
** Riemann integral

* Condenced Linear algebra

** Introduction
Linear Algebra is an interesting subject that broadens your horizon if you first
studied analyisis. One possible way to go around studying it is through the lens
of Category theory -- the alternative view to look at mathematics as a whole
(the "standard view" being Set theory).

one of the most important concepts to understand are:
- Linear (in)dependance
- Linear equation
- Linear system
- Relations between Matrices and Linear systems.

as long as you /understand/ these things, the rest of Linear Algebra should be
easier to grasp (hopefully).

** Tiny bit of combinatorics
this is useful for understanding Leibniz's formula for calculating the
Determinant.
there are transpositions and permutations.

** Gauss-Jordan algorithm
this is something you'll be doing a lot, so get used to it.


** Matrices, Properties
*** Dimension
*** Rank
*** Span
** rng() <- Ring? Rang? ≠ Rank
** Morphisms (move to Category theory)

*** Endomorphism
**** Automorphism

*** Homomorphism
*** Isomorphism
** Scalar product(s)
** Hermetic-Bilinear-Sesquilinear functions
** Orthogonality

** Gram-Schmidt process
∫{}<>[]`´() /from:/ /to:/ /of/
* Condenced {Discrete math ⋃ Numerical analysis}
** Numerical stability
